version: "3"
services:
  navidrome:
    container_name: bot-clony
    image: bot-clony
    # user: 1000:1000 # should be owner of volumes
    restart: always
    volumes:
      - "./bot.db:/usr/src/bot/bot.db"
    network_mode: bridge
    env_file:
      - ./.env
    options:
        max-size: "5m"
        max-file: "1"

